// Keep factor counts, identical-combination labels and V selection tied to evidence.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../app/static/app.js'),'utf8');
const S={models:[],experiments:[]};const ctx={S};vm.createContext(ctx);
vm.runInContext(source.slice(0,source.indexOf('const pages =')),ctx);
assert.equal(ctx.researchMethod({generator:'fixed',reward_mode:'trade_delta'}).label,'固定因子基准');
assert.equal(ctx.researchMethod({generator:'random',reward_mode:'trade_delta'}).label,'随机搜索新因子');
assert.match(ctx.researchMethod({generator:'ppo',reward_mode:'single_ic'}).label,/单因子/);
assert.match(ctx.researchMethod({generator:'ppo',reward_mode:'trade_delta'}).label,/组合交易增量/);
assert.equal(ctx.experimentTitle({name:'用户自定义 · 12因子研究'}),'用户自定义 · 12因子研究');
assert.match(ctx.experimentTitle({name:'raw500-v1-mechanism · E / 7',protocol:{generator:'ppo',reward_mode:'trade_delta',seed:7}}),/500股机制验收.*种子 7/);
assert.equal(ctx.poolChange({a:.4,b:.6},{b:.6,a:.4,c:0}),'因子与权重均相同');
assert.equal(ctx.poolChange({a:.4,b:.6},{a:.5,b:.5}),'因子相同，权重已变化');
assert.equal(ctx.poolChange({a:.4,b:.6},{a:.4,c:.6}),'因子组成已变化');
const p={initial_expressions:['a','b'],initial_weights:[.4,.6]};
const e={id:'first',protocol:p,selection:{frozen_model_id:'frozen',rule:'max_V_J_earliest_tie_no_refit',checkpoints:[{batch_id:2,objective:1,weights:{a:.5,b:.5}},{batch_id:1,objective:1,weights:{a:.4,b:.6}},{batch_id:3,objective:0,weights:{z:1}}]}};
assert.equal(ctx.frozenCombination(e).batch,1,'ties must resolve to earliest batch, not latest pool');
assert.equal(ctx.frozenCombination({...e,selection:{...e.selection,rule:'unknown'}}),null,'unknown selection rules must not fabricate frozen weights');
const weights=Object.fromEntries(Array.from({length:12},(_,i)=>['factor'+i,1/12]));weights.zero=0;
S.models=[{version_id:'model',weights,source:{selected_batch:3}}];
assert.equal(Object.keys(ctx.activePool(ctx.frozenCombination({...e,model_version:'model'}).weights)).length,12);
S.experiments=[e,{...e,id:'second'}];
assert.match(ctx.experimentResultCell(e),/与起点相比：因子与权重均相同/);
assert.match(ctx.experimentResultCell(e),/<br>与另外 1 个实验的因子及权重相同/);
assert.match(ctx.factorWeightsTable({return_20:.4,'neg(volatility_20)':.6}),/20日收益率/);
assert.match(ctx.factorWeightsTable({'<unsafe>':1}),/&lt;unsafe&gt;/);
vm.runInContext(source.slice(source.indexOf('function experimentFactors(e)'),source.indexOf('function experimentBacktest(e)')),ctx);
const markup=ctx.experimentFactors({...e,pools:[{batch_id:1,pool_version:0,weights:{a:.4,b:.6}}],trials:[],run_status:{pool:{a:.4,b:.6}}});
assert.match(markup,/1\. 初始因子池/);assert.match(markup,/2\. 每批结束/);assert.match(markup,/3\. 冻结组合/);
assert.match(markup,/不等于效果提高/);
console.log('research presentation evidence tests passed');
