const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx={S:{models:[],experiments:[]}};vm.createContext(ctx);
for(const name of ['research-ui.js','research-backtest.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../app/static',name),'utf8'),ctx);
const source=fs.readFileSync(path.join(__dirname,'../app/static/app.js'),'utf8');
vm.runInContext(source.slice(0,source.indexOf('const pages =')),ctx);
const R=ctx.ResearchUI,B=ctx.ResearchBacktest;
assert.equal(R.pct(null),'未记录');assert.equal(R.pct(0),'0%');
const monthly=R.monthly([{date:'2025-01-01',net_return:.1},{date:'2025-01-02',net_return:-.1},{date:'2025-02-01',net_return:0}]);
assert.ok(Math.abs(monthly[0].value-(-.01))<1e-12,'monthly returns must compound net daily returns');
assert.equal(monthly[1].value,0,'zero is observed, not missing');
const chart=R.lineChart([{x:'<bad>',y:1},{x:'2025-01-02',y:1}],{title:'NAV'});
assert.ok(!chart.includes('NaN'));assert.ok(chart.includes('&lt;bad&gt;'));assert.ok(chart.includes('polyline'));
assert.match(R.bars([{label:'first',value:-.2},{label:'second',value:-.1,selected:true}],{title:'V目标'}),/已选中/);
const entries=[{artifact_id:'f',segment:'F',roles:['search']},{artifact_id:'e',segment:'E',roles:['adopted','candidate']},{artifact_id:'v',segment:'V',roles:['validation','selected']},{artifact_id:'t',segment:'T',roles:['final_test']}];
assert.equal(B.preferred(entries).artifact_id,'t');
assert.equal(B.preferred(entries.slice(0,3)).artifact_id,'v');
assert.equal(B.filtered(entries,'outcomes').length,3);assert.equal(B.filtered(entries,'search').length,1);
assert.equal(B.filtered(entries,'candidates').length,1,'shared adopted/candidate evidence remains discoverable');
const S=ctx.S;
S.backtest={segment:'T',weights:{return_20:1},result:{daily:[{date:'2025-01-02',nav:99,net_return:-.01,cash:4,stock_value:95,fee:1}],metrics:{total_return:-.01,max_drawdown:0},orders:[{date:'2025-01-02',code:'000001',requested:100,shares:0,side:'buy',reason:'cash_or_minimum_fee'}],actions:[{date:'2025-01-02',code:'000001',previous_shares:100,share_multiplier:2,cash_received:30}]}};
S.backtestDate='2025-01-02';S.backtestDetail='orders';S.backtests=entries;S.backtestId='t';
const h=vm.runInContext('({S,esc,num,when,metric,btn,option,notice,empty,table,td,json,factorWeightsTable,R:ResearchUI})',ctx);
assert.match(B.day(h),/最低手续费/);assert.ok(!B.day(h).includes('<details open'));
S.backtestDetail='actions';assert.match(B.day(h),/到账现金/);assert.match(B.day(h),/30/);
assert.match(B.view({protocol:{initial_cash:100,top_k:50,segments:{T:['2025-01-01','2025-01-31']}}},h),/回撤/);
assert.ok(!B.view({protocol:{}},h).includes('<details open'));
console.log('research backtest semantics, compounding, charts and ledger tests passed');
